name: CI (build + artifacts)

on:
  push:
    branches: [ master, feature/** ]
  pull_request:

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CSC_IDENTITY_AUTO_DISCOVERY: "false"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 24
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Cache electron/electron-builder
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/electron
            ~/.cache/electron-builder
            ~/Library/Caches/electron
            ~/Library/Caches/electron-builder
            %LOCALAPPDATA%/electron/Cache
            %LOCALAPPDATA%/electron-builder/Cache
          key: ${{ runner.os }}-electron-cache-${{ hashFiles('package-lock.json') }}

      - name: Install deps
        run: npm ci

      - name: Build app code (TS)
        run: |
          npm run compile --if-present

      - name: Electron build (no publish)
        run: npm run dist:ci

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-pane-${{ matrix.os }}
          path: release/**
          if-no-files-found: error
